server:
  port: 8080
  application-name: getway-service
eureka:
  client:
    fetch-registry:  true
    register-whith-eureka:  true
    service-url:
      default-zone:  http://localhost:8761/eureka
    instance:
       hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
      - id: usuario-service
        uri: lb://usuario-service
        predicates:
          - Path=/usuario/**
      - id: carro-service
        uri: lb://carro-service
        predicates:
          - Path=/carro/**
      - id: moto-service
        uri: lb://moto-service
        predicates:
          - Path=/moto/**
      
