server:
  port: 8080
  application-name: gateway-service
eureka:
  client:
    fetch-registry:  true
    register-whith-eureka:  true
    service-url:
      default-zone:  http://localhost:8761/eureka
    instance:
       hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
      - id: usuario_service
        uri: lb://usuario_service
        predicates:
          - Path=/usuario/**
      - id: carro_service
        uri: lb://carro_service
        predicates:
          - Path=/carro/**
      - id: moto_service
        uri: lb://moto_service
        predicates:
          - Path=/moto/**
      
