server:
  port: 8085
spring:
  cloud:
    config:
      server:
        git:
          default-label: cofig-server
          uri: https://github.com/acruiz86/Microservice/tree/Servidor_de_Configuracion
          search-paths:  config_data
  application:
    name: config_server
